### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by oliviathevampire** [EnnuiL/LibZoomer#5]
Hey! I was just wondering, will this mod get an update for 1.18.2? I've heard they've done huge tag ands registry changes which probably will break this mod

**Comment by EnnuiL** [comment]
Since we don't touch tags directly and only through the Fabric API, I don't think there will be any issues, and Ok Zoomer (an user of LibZoomer) on 1.18.2-rc1 hasn't caused any crashes; However, since Quilt Mappings had refactored input-related mappings, I'll possibly do a small update anyway in order to keep the code up-to-date

**Comment by EnnuiL** [comment]
oh god, the part that touched tags did indeed explode; 0.3.1+1.18.2 is on its way

**Comment by EnnuiL** [comment]
Fixed on 0.4.0+1.18.2
